import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers
        refetchInterval={30} //Sessionu her 30 saniyede bir refetch edecektir, böylece sessionın stateini her 5 dakikada bir güncelleriz. Burasının valuesi her zaman Sessionın `maxAge` propertysinden daha KUCUK olmalıdır
        refetchOnWindowFocus={true} //Window focus olduğunda sessionı refetch edecektir; böylece sessionın stateini her window veya tab değişiminde bir günncelleriz
      >
        <body>{children}</body>
      </Providers>
    </html>
  );
}
